### ISSUE TITLE
Unify coding style!

### ISSUE THREAD

**Issue by barthap** [barthap/inpg-checkers#10]
### Unless we resolve this, I WON'T continue my work

We need to unify coding style and file encoding! I suggest following _[PEP 8](https://www.python.org/dev/peps/pep-0008/)_ coding style, which includes:
- 4 spaces instead of tabs
- space after `#` in comment, `# like this`
- `CamelCase` class names
- `snake_case` for functions, methods, properties, variables
- one blank (empty) line at end of file
- two blank lines before class or global function definition
- one blank line between class methods
- some more, you can read in the link above
PyCharm (at least for me) gives me hints and underlines code, with inconsistent syntax:
![PyCharm hints](https://user-images.githubusercontent.com/278340/40215769-ced875a0-5a62-11e8-8edb-3b39ba7c3a4e.png)

But most important for me is that we should decide tabs or spaces. Why? Look how our commits look:
![Diff view](https://user-images.githubusercontent.com/278340/40215725-74769326-5a62-11e8-9e2c-aa3e573f02b9.png)

Instead of single lines, whole file is replaced and I cannot see the commit changes!

We should decide: _TABS_ or _SPACES_ and then in _File -> Settings (Ctrl+Alt+S)_ we should have all the same settings, at least these on the screen:
![settings](https://user-images.githubusercontent.com/278340/40215895-a278d71a-5a63-11e8-826a-f0259c246bf8.png)

**Comment by barthap** [comment]
I don't care if I'm gonna use tabs or spaces, but we all should use the same!

**Comment by freestylofil** [comment]
@barthap could we please use tab?

**Comment by mizeria298** [comment]
@barthap if it doesn't matter for you let's just stick to tabs

**Comment by barthap** [comment]
-.-

**Comment by barthap** [comment]
# EVERYONE please set it like this!
It is in **_File -> Settings (Ctrl+Alt+S)_**
![2018-05-18 6](https://user-images.githubusercontent.com/278340/40242284-852b3f04-5abd-11e8-9cb7-43eaac66bfa7.png)
