### ISSUE TITLE
draw_board_pieces: AttributeError: 'NoneType' object has no attribute 'color'

### ISSUE THREAD

**Issue by freestylofil** [barthap/inpg-checkers#3]
Function draw_board_pieces returns an error while checking if-statements

**Comment by barthap** [comment]
Give more details please, maybe traceback?

**Comment by freestylofil** [comment]
This is what I got.

> line 72,in draw_board_pieces
if board.matrix[x][y].piece.color == RED and board.matrix[x][y].piece.king == False:
AttributeError: 'NoneType' object has no attribute 'color'

I have no idea why the fuction recognises `piece`s as a NoneType

**Comment by barthap** [comment]
I understand you are in `boardrender` branch.
### Overview
As you see, if statements in `draw_board_pieces()` reference `color` of `Piece` class. But error says, that `board.matrix[x][y].piece` is `NoneType`, which has no attributes. So you are trying to reference attribute of object, that does not exist.
`board.matrix` should be an 8x8 array of `Square` objects. It is initialized in `Board.generate_board()`. But when you look at the function, you will see that:
1. Firstly, an 8x8 array of `None` is created
2. Each array element is initialized as `Square` with color depending on `x` and `y` being even or odd.
3. **SOME** elements on `BLACK` fields have their `piece` attribute initialized. "Some" is not "all" so here is your problem. Some elements are still None.

### Solution
At the beginning of `draw_board_pieces` you have to check if `board.matrix[x][y].piece` is not a `None`

**Comment by freestylofil** [comment]
Thanks @barthap!
I implemented your solution. Moreover, I created a function `coordRename((x,y))` to easily type board coordinates.
