### ISSUE TITLE
Can only move piece once

### ISSUE THREAD

**Issue by freestylofil** [barthap/inpg-checkers#8]
With the current status of the `gamemechanics` branch, I expected I could move the blue pieces infinitely, because there is no mechanism of switching turns.
The game, however allows me to move one piece once.
What is the state of `GameScene.selected_square` after passing it as an argument to remove_piece?

**Comment by barthap** [comment]
I have just commited changes allowing to switch turns.
Also, after moving a piece `selected_square` does not change so you have to None it manually. I've already fixed this
